export const defaultStarterCharacters = [
    {
        id: "lyra",
        name: "Lyra Vex",
        race: "Tiefling",
        className: "druid",
        level: 5,
        hp: 31,
        maxHp: 38,
        tempHp: 4,
        ac: 14,
        speed: 30,
        initiative: 3,
        abilities: { FOR: 8, DES: 14, CON: 13, INT: 12, SAB: 10, CAR: 18 },
        proficiency: 3,
        spellAbility: "CAR",
        spellSlots: [0, 4, 3, 2, 0, 0, 0, 0, 0],
        spentSlots: [0, 1, 0, 0, 0, 0, 0, 0, 0],
        gold: 84,
        silver: 12,
        copper: 8,
        avatar: "LV",
        spells: ["Explosão Mística", "Feitiço", "Armadura de Agathys", "Fome de Hadar"],
        equipment: [
            { name: "Cajado de freixo", qty: 1 },
            { name: "Kit de aventureiro", qty: 1 },
            { name: "Poção de cura", qty: 2 },
        ],
    },
    {
        id: "bram",
        name: "Bram Stonehand",
        race: "Anão",
        className: "fighter",
        level: 4,
        hp: 42,
        maxHp: 42,
        tempHp: 0,
        ac: 18,
        speed: 25,
        initiative: 1,
        abilities: { FOR: 18, DES: 12, CON: 16, INT: 9, SAB: 11, CAR: 10 },
        proficiency: 2,
        spellAbility: "SAB",
        spellSlots: [0, 0, 0, 0, 0, 0, 0, 0, 0],
        spentSlots: [0, 0, 0, 0, 0, 0, 0, 0, 0],
        gold: 36,
        silver: 4,
        copper: 16,
        avatar: "BS",
        spells: [],
        equipment: [
            { name: "Machado de batalha", qty: 1 },
            { name: "Escudo de carvalho", qty: 1 },
        ],
    },
]